### API 1
GET http://localhost:3000/players/

### API 2
POST http://localhost:3000/players/
Content-Type: application/json

{
  "playerName": "Vishal",
  "jerseyNumber": 17,
  "role": "Bowler"
}

### API 3
GET http://localhost:3000/players/16


### API 4
PUT http://localhost:3000/players/15
Content-Type: application/json

{
  "playerName": "Maneesh",
  "jerseyNumber": 55,
  "role": "All-rounder"
}

### API 5
DELETE http://localhost:3000/players/15